medatom/make-live-usb: Add more places to look for mbr.bin
The directory depends on the distribution used. Note this does not cover
all possibilities, e.g. Ubuntu which uses an 'mbr' subdir.

Signed-off-by: Dirk Leber <dirk.leber@avionic-design.de>
Change-Id: Id92b2da0003bb7349e11cf52e68f1136579be9df
Reviewed-on: http://review.adnet.avionic-design.de/5285
Reviewed-by: Bert van Hall <bert.vanhall@avionic-design.de>

diff --git a/medatom/make-live-usb b/medatom/make-live-usb
--- a/medatom/make-live-usb
+++ b/medatom/make-live-usb
@@ -34,7 +34,18 @@ device="$1"
 ,,L
 EOF
 
-cat /usr/lib/syslinux/mbr.bin > ${device}
+for directory in /usr/lib/syslinux /usr/share/syslinux; do
+    if test -f "$directory/mbr.bin"; then
+	cat "$directory/mbr.bin" > ${device}
+	mbr_installed=yes
+    fi
+done
+
+if test "x$mbr_installed" != "xyes"; then
+    echo "MBR not found, try installing syslinux"
+    exit 1
+fi
+
 wait_for_partition ${device}1
 format_partition ${device}1 ext4 boot
 wait_for_partition ${device}2
