medatom/make-live-usb: check for extlinux
Avoids a confusing error near the end of the script.

Change-Id: I328776ea590b555789c0a05da2371c4ce9bda40f
Signed-off-by: Bert van Hall <bert.vanhall@avionic-design.de>
Reviewed-on: http://review.adnet.avionic-design.de/5469
Reviewed-by: Hendrik Lippek <hendrik.lippek@avionic-design.de>

diff --git a/medatom/make-live-usb b/medatom/make-live-usb
--- a/medatom/make-live-usb
+++ b/medatom/make-live-usb
@@ -21,6 +21,11 @@ format_partition()
 	fi
 }
 
+if ! type extlinux >/dev/null 2>&1; then
+	echo 'extlinux is required for this script.'
+	exit 1
+fi
+
 if [ "x$1" = "x" ]; then
 	echo "usage: $0 device"
 	exit 1
