medatom/rootfs: fix usb-power script for systemd
The usb-power script was completely broken and is now fixed. Add the
new-style label the device gets assigned by recent kernels.

Change-Id: I7353d8dbd4f9171a8d4f9fd7d4e70f9dc81eabd6
Signed-off-by: Bert van Hall <bert.vanhall@avionic-design.de>
Reviewed-on: http://review.adnet.avionic-design.de/4553
Reviewed-by: Nikolaus Schulz <nikolaus.schulz@avionic-design.de>

diff --git a/medatom/rootfs/src/usr/lib/systemd/usb-power b/medatom/rootfs/src/usr/lib/systemd/usb-power
--- a/medatom/rootfs/src/usr/lib/systemd/usb-power
+++ b/medatom/rootfs/src/usr/lib/systemd/usb-power
@@ -1,22 +1,23 @@
 #!/bin/sh -e
 
-function find_gpiochip
+BASE='x'
+
+find_gpiochip()
 {
 	for f in /sys/class/gpio/gpiochip*; do
-		LABEL=`cat $f/label`
+		LABEL=$(cat "$f/label")
 		if [ "$LABEL" = "$1" ]; then
-			cat $f/base
+			BASE=$(cat "$f/base")
 			return 0
 		fi
 	done
 	return 1
 }
 
-BASE=$(find_gpiochip "0000:05:00.0")
-if [ $BASE = "" ]; then
-	echo "Error: gpio chip not found."
-	exit 1
-fi
+# retry with old-style naming
+find_gpiochip "gpio-ad64p" || find_gpiochip "0000:05:00.0"
 
-echo $(($BASE+15)) > /sys/class/gpio/export
-echo high > /sys/class/gpio/gpio$(($BASE+15))/direction
+[ "$BASE" = "x" ] && { echo "Error: gpio chip not found."; exit 1; }
+
+echo $((BASE+15)) > /sys/class/gpio/export
+echo high > /sys/class/gpio/gpio$((BASE+15))/direction
