medcom-wide: Add the boot script to the make-sdcard
To boot from a newer u-boot the boot script is necessary.

Change-Id: If63366a6a47602a023ffa6e126e6fdcbf558e8cd
Signed-off-by: Nicolas Bänisch <nicolas.baenisch@avionic-design.de>
Reviewed-on: http://review.adnet.avionic-design.de/3827
Reviewed-by: Bert van Hall <bert.vanhall@avionic-design.de>

diff --git a/medcom-wide/make-sdcard b/medcom-wide/make-sdcard
--- a/medcom-wide/make-sdcard
+++ b/medcom-wide/make-sdcard
@@ -7,6 +7,7 @@ def=$pbsroot/defconfig
 imgdir=$pbsroot/img
 uImg="$imgdir/uImage"
 rootImg="$imgdir/rootfs.img"
+bootScript="$imgdir/boot.scr.uimg"
 
 
 log_action_begin_msg()
@@ -97,6 +98,16 @@ if test -d "$imgdir" && test -f "$uImg" && test -f "$rootImg"; then
 	log_action_end_msg $?
 else
 	echo "Images not found...$uImg and/or $rootImg"
+	log_action_end_msg 1
+fi
+
+if test -f "$bootScript"; then
+	log_action_begin_msg "  Copy boot script"
+		cp "$bootScript" "$mp/boot"
+	log_action_end_msg $?
+else
+	echo "Boot script $bootScript  not found!"
+	log_action_end_msg 1
 fi
 
 log_action_begin_msg "Unmounting rootfs storage"
