medcom-wide/rootfs: Autodetect gpios in helper scripts.
Signed-off-by: Julian Scheel <julian@jusst.de>
Reviewed-by: Soeren Grunewald <soeren.grunewald@avionic-design.de>
Tested-by: Soeren Grunewald <soeren.grunewald@avionic-design.de>

diff --git a/medcom-wide/rootfs/src/usr/bin/enable-lan b/medcom-wide/rootfs/src/usr/bin/enable-lan
--- a/medcom-wide/rootfs/src/usr/bin/enable-lan
+++ b/medcom-wide/rootfs/src/usr/bin/enable-lan
@@ -10,6 +10,24 @@ if [ "$#" != "1" ]; then
 	exit 1
 fi
 
+function find_gpiochip
+{
+        for f in /sys/class/gpio/gpiochip*; do
+                LABEL=`cat $f/label`
+                if [ $LABEL == $1 ]; then
+                        echo "${f:24}"
+			return 0
+                fi
+        done
+	return 1
+}
+
+BASE=$(find_gpiochip "gpio-adnp")
+if [ $BASE == "" ]; then
+	echo "Error: gpio chip not found."
+	exit 1
+fi
+
 if [ "$1" = "on" ]; then
 	VALUE="high"
 elif [ "$1" = "off" ]; then
@@ -19,8 +37,9 @@ else
 	exit 1
 fi
 
-echo 456 > /sys/class/gpio/export
-echo $VALUE > /sys/class/gpio/gpio456/direction
-echo 456 > /sys/class/gpio/unexport
+GPIO_LAN=$[$BASE+8]
+echo $GPIO_LAN > /sys/class/gpio/export
+echo $VALUE > /sys/class/gpio/gpio$GPIO_LAN/direction
+echo $GPIO_LAN > /sys/class/gpio/unexport
 
 exit 0
diff --git a/medcom-wide/rootfs/src/usr/bin/reset-medcom b/medcom-wide/rootfs/src/usr/bin/reset-medcom
--- a/medcom-wide/rootfs/src/usr/bin/reset-medcom
+++ b/medcom-wide/rootfs/src/usr/bin/reset-medcom
@@ -1,10 +1,28 @@
 #!/bin/sh -e
 
-echo 508 > /sys/class/gpio/export
-echo 509 > /sys/class/gpio/export
-echo 510 > /sys/class/gpio/export
-echo 511 > /sys/class/gpio/export
-echo low > /sys/class/gpio/gpio508/direction
-echo high > /sys/class/gpio/gpio509/direction
-echo low > /sys/class/gpio/gpio510/direction
-echo high > /sys/class/gpio/gpio511/direction
+function find_gpiochip
+{
+        for f in /sys/class/gpio/gpiochip*; do
+                LABEL=`cat $f/label`
+                if [ $LABEL == $1 ]; then
+                        echo "${f:24}"
+			return 0
+                fi
+        done
+	return 1
+}
+
+BASE=$(find_gpiochip "gpio-adnp")
+if [ $BASE == "" ]; then
+	echo "Error: gpio chip not found."
+	exit 1
+fi
+
+echo $[$BASE+60] > /sys/class/gpio/export
+echo $[$BASE+61] > /sys/class/gpio/export
+echo $[$BASE+62] > /sys/class/gpio/export
+echo $[$BASE+63] > /sys/class/gpio/export
+echo low > /sys/class/gpio/gpio$[$BASE+60]/direction
+echo high > /sys/class/gpio/gpio$[$BASE+61]/direction
+echo low > /sys/class/gpio/gpio$[$BASE+62]/direction
+echo high > /sys/class/gpio/gpio$[$BASE+63]/direction
